### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mikegleasonjr** [kmarzic/openwrt_mikrotik_cap_ac#1]
Hi, thank you very much for your releases.

I successfully used 2-3 of them in the past, I have 3 Cap AC at home running OpenWRT thanks to your builds.

I am just wondering, to they include now these changes as well: https://github.com/openwrt/openwrt/pull/4055#issuecomment-943502725 ?

Thanks!

**Comment by kmarzic** [comment]
Hi,

I am just building https://github.com/rusitschka/openwrt-mikrotik-hap-ac2.
Now, it is based on 5.10 kernel (previous was 5.4 kernel).

Here is the list of included changes: 
https://github.com/john-tho/openwrt/pull/2/commits
Changes from https://github.com/openwrt/openwrt/pull/4679/commits are included.

I hope that cAP AC will soon be accepted in OpenWRT.

Regards

**Comment by mikegleasonjr** [comment]
> I hope that cAP AC will soon be accepted in OpenWRT.

Yes I hope too.

Thanks for your efforts!
